2018-02-28T17:01:13.112Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Model violation in instance outbound.logistics.vehicle.Car#0001 field manufacturedDate has value 1519837273075 (number) expected type DateTime)
    at /home/chris/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-28T17:01:13.113Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Model violation in instance outbound.logistics.vehicle.Car#0001 field manufacturedDate has value 1519837273075 (number) expected type DateTime)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Model violation in instance outbound.logistics.vehicle.Car#0001 field manufacturedDate has value 1519837273075 (number) expected type DateTime)\n\n    at _initializeChannel.then.then.then.then.catch (/home/chris/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
